# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://gpengtao.github.io/gpt.github.io
date_format: "ordinal"
title: èŠ±è½ä¸æŠ˜æ
subtitle: "ç¥å…½ä¿ä½‘ğŸ™æ°¸æ— bug"
description: "gptçš„ä¸ªäººåšå®¢"
keywords: æœ‰èŠ±å ªæŠ˜ç›´é¡»æŠ˜ï¼Œè«å¾…æ— èŠ±ç©ºæŠ˜æ
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Pengtao Geng
organization: gpengtao
organization_url: https://gpengtao.github.io/gpt.github.io/
github_username: gpengtao
location: Beijing, China
email: gpengtao@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: é¦–é¡µ

#  -
#    href: /categories/
#    label: åˆ†ç±»

#   -
#     href: /archives/
#     label: å½’æ¡£

#  -
#    href: /wiki/
#    label: ç»´åŸº
#
#  -
#    href: /links/
#    label: é“¾æ¥

  -
    href: /about/
    label: å…³äº

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: gpengtao/gpt.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
## !!!é‡è¦!!! è¯·ä¿®æ”¹ä¸‹é¢è¿™äº›ä¿¡æ¯ä¸ºä½ è‡ªå·±ç”³è¯·çš„
## !!!Important!!! Please modify infos below to yours
## https://disqus.com
#disqus:
#    username:
## https://imsun.net/posts/gitment-introduction/
#gitment:
#    owner: gpengtao
#    repo: blog-comments
#    oauth:
#        client_id: ddf32b02a446baa89407
#        client_secret: 66cfb9a1f5eeba62da2b256f6b1ea52247b78a56
## https://github.com/gitalk/gitalk#install
gitalk:
    owner: gpengtao
    repo: blog-comments
    clientID: ddf32b02a446baa89407
    clientSecret: 66cfb9a1f5eeba62da2b256f6b1ea52247b78a56
## åœ¨ä½¿ç”¨å…¶å®ƒè¯„è®ºç»„ä»¶æ—¶å¯ç‚¹å‡»æ˜¾ç¤º Disqus
#lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # æ˜¯å¦æ”¯æŒå…¨æ–‡æœç´¢
    fulltext: false
    # æœ€å¤šæ˜¾ç¤ºå¤šå°‘æ¡æœç´¢ç»“æœ
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
